### ISSUE TITLE
xu3 board

### ISSUE THREAD

**Issue by Vampire-Vx** [RedCarrottt/odroid-xu3-power#2]
Do u have any idea where to buy a xu3 board?(not lite version)
Or are u willing to sell it?

**Comment by RedCarrottt** [comment]
Hello,
Hardkernel still seems to be selling Odroid-XU4.
Since Odroid-XU3 and XU4 have same chipsets, you can also try this script on the Odroid-XU4.

**Comment by Vampire-Vx** [comment]
> Hello,
> Hardkernel still seems to be selling Odroid-XU4.
> Since Odroid-XU3 and XU4 have same chipsets, you can also try this script on the Odroid-XU4.

Thansk for your kindly reply. But I need the energy sensor to do benchmarking on cpu cores....
